region                                   = "asia-east1"
zone                                     = "asia-east1-b"
service_name                             = "scstore"
benchmark_service_account_name           = "benchmark@role-play-web-app-host-project.iam.gserviceaccount.com"
gce_machine_type                         = "e2-standard-2"
gce_image_name                           = "debian-cloud/debian-10"
cloudsql_machine_type                    = "db-custom-1-3840"
database_scstore_password                = "scstore"